name: Tests / E2E Upgrade
on: workflow_dispatch

jobs:
  upgrade-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: TestV4ToV5ChainUpgrade
            chain-image: ghcr.io/cosmos/ibc-go-simd
            chain-a-tag: v4.2.0
            chain-b-tag: v4.2.0
            chain-upgrade-tag: v5.1.0
          - test: TestV5ToV6ChainUpgrade
            chain-image: ghcr.io/cosmos/ibc-go-icad
            chain-binary: icad
            chain-a-tag: v0.3.5
            chain-b-tag: v0.3.5
            chain-upgrade-tag: v0.4.1
          - test: TestV6ToV7ChainUpgrade
            chain-image: ghcr.io/cosmos/ibc-go-simd
            chain-binary: simd
            chain-a-tag: v6.0.0
            chain-b-tag: v6.0.0
            chain-upgrade-tag: v7.0.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run e2e upgrade test
        run: |
          cd e2e
          make e2e-test entrypoint=TestUpgradeTestSuite test=${{ matrix.test }}
        env:
          CHAIN_IMAGE: ${{ matrix.chain-image }}
          CHAIN_BINARY: ${{ matrix.chain-binary }}
          CHAIN_A_TAG: ${{ matrix.chain-a-tag }}
          CHAIN_B_TAG: ${{ matrix.chain-b-tag }}
          CHAIN_UPGRADE_TAG: ${{ matrix.chain-upgrade-tag }}
